#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Mon Jul 23 22:12:58 2012

import wx
from MyFrame import MyFrame

class wxKarel(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class wxKarel

if __name__ == "__main__":
    import gettext
    gettext.install("Karel") # replace with the appropriate catalog name

    Karel = wxKarel(0)
    Karel.MainLoop()
